export const AREA_OPTIONS = [
  "Aeronautical engineering",
  "Agriculture",
  "Antennas",
  "Applied Physics",
  "Architecture",
  "Architecture & Civil Engineering",
  "Artificial intelligence",
  "Automotive engineering",
  "Automotive, Aeronautical & Mechanical Engineering",
  "Biometrics",
  "Biotechnology",
  "CAD",
  "Chemical, Polymer & Petroleum Engineering",
  "Civil engineering",
  "Climate change",
  "Communication theory",
  "Communications",
  "Computer architecture",
  "Computer networks",
  "Computer networks - applications",
  "Computer networks - enterprise",
  "Computer networks - management",
  "Computer networks - measurements",
  "Computer networks - optical",
  "Computer networks - peer-to-peer",
  "Computer networks - security",
  "Computer networks - sensor",
  "Computer networks - switching",
  "Computer vision",
  "Computing & Communications",
  "Consumer electronics",
  "Control systems",
  "Cryptography",
  "Cultural Studies",
  "Data Mining",
  "Diagnostic Radiology",
  "E-Commputing (e-learning, e-government, e-commerce, etc.)",
  "eHealth",
  "Electrical & Power Engineering",
  "Electrical and computer engineering",
  "Electrical engineering",
  "Electron devices",
  "Energy",
  "Engineering",
  "Entrepreneurship and innovation",
  "Environment",
  "Food technology",
  "Human Factors and Social Issues",
  "Humanities",
  "Image analysis",
  "Information Systems",
  "Information theory",
  "Language Study",
  "Literature",
  "Management Science",
  "Mechanical Engineering",
  "Mechatronics",
  "Medical Lab Technology",
  "Medical Physics and Biomedical Engineering",
  "Medicine",
  "Microelectronics",
  "Mobile computing",
  "Motion Imaging",
  "Multimedia",
  "Neural networks",
  "Nursing & Midwifery",
  "Online education",
  "Operating systems",
  "Parallel and Distributed Computing",
  "Performance",
  "Pharmacology",
  "Poetic studies",
  "Political Science",
  "Polymer & petroleum engineering",
  "Powerline transmission",
  "Product safety",
  "Quality Assurance",
  "Radio communications",
  "Reliability",
  "RF and microwave engineering",
  "Risk Management",
  "Robotics",
  "Satellite and space communications",
  "Science and technology policy",
  "Security",
  "Semiconductor",
  "Sensors",
  "Service Sciences",
  "Signal processing",
  "Social and Behavioral Science",
  "Space Science and Communication",
  "Sports & Physical Education",
  "System engineering",
  "Technology management",
  "Television broadcast",
  "Test only",
  "Water issues",
  "Wireless communications",
] as const

export const SOCIETY_SPONSOR_OPTIONS = [
  { value: "ACM", label: "ACM (ACM)" },
  { value: "AESJ", label: "AESJ (Atomic Energy Society of Japan)" },
  { value: "AIAA", label: "AIAA (American Institute of Aeronautics and Astronautics, Inc.)" },
  { value: "AIAT", label: "AIAT (Artificial Intelligence Association of Thailand)" },
  { value: "AIJ", label: "AIJ (Architectural Institute of Japan)" },
  { value: "ASCE", label: "ASCE (American Society of Civil Engineers)" },
  { value: "ASEE", label: "ASEE (American Society for Engineering Education)" },
  { value: "ASME", label: "ASME (American Society of Mechanical Engineers)" },
  { value: "BCS", label: "BCS (British Computer Society)" },
  { value: "BMFSA", label: "BMFSA (Biomedical Fuzzy Systems Association)" },
  { value: "BMS", label: "BMS (The Behaviormetric Society of Japan)" },
  { value: "CIC", label: "CIC (China Institute of Communications)" },
  { value: "CITT", label: "CITT (The Association of Council of IT Deans in Thailand)" },
  { value: "CNC-URSI", label: "CNC-URSI (Canadian National Committee of the International Union of Radio Science)" },
  { value: "CRC", label: "CRC (Communications Research Institute - Canada)" },
  { value: "ECTI", label: "ECTI (Electrical Engineering/Electronics, Computer, Communications and Information Technology Association)" },
  { value: "Engineers Australia", label: "Engineers Australia" },
  { value: "EOS", label: "EOS (European Optical Society)" },
  { value: "ETRI", label: "ETRI (Electronic and Telecommunications Research Institute - South Korea)" },
  { value: "EuMA", label: "EuMA (European Microwave Association)" },
  { value: "EurAAP", label: "EurAAP (European Association on Antennas and Propagation)" },
  { value: "EURASIP", label: "EURASIP (European Association for Signal Processing)" },
  { value: "FLSI", label: "FLSI (Fuzzy Logic Systems Institute)" },
  { value: "GI", label: "GI (Gesellschaft für Informatik)" },
  { value: "Greek Computer Society", label: "Greek Computer Society" },
  { value: "HIS", label: "HIS (Human Interface Society)" },
  { value: "IAPR", label: "IAPR (IAPR)" },
  { value: "IChemE", label: "IChemE (Institution of Chemical Engineers)" },
  { value: "ICRP", label: "ICRP (The Institution of Creative Research Professionals)" },
  { value: "ICTPS", label: "ICTPS (ICT Platform Society)" },
  { value: "IEE", label: "IEE (Institution of Engineering and Technology)" },
  { value: "IEEE", label: "IEEE (Institute of Electrical and Electronics Engineers)" },
  { value: "IEEE AESS", label: "IEEE AESS (IEEE Aerospace and Electronic Systems Society)" },
  { value: "IEEE APS", label: "IEEE APS (IEEE Antennas and Propagation Society)" },
  { value: "IEEE BTS", label: "IEEE BTS (IEEE Broadcast Technology Society)" },
  { value: "IEEE CASS", label: "IEEE CASS (IEEE Circuits and Systems Society)" },
  { value: "IEEE CES", label: "IEEE CES (IEEE Consumer Electronics Society)" },
  { value: "IEEE CIS", label: "IEEE CIS (IEEE Computational Intelligence Society)" },
  { value: "IEEE Computer", label: "IEEE Computer (IEEE Computer Society)" },
  { value: "IEEE ComSoc", label: "IEEE ComSoc (IEEE Communications Society)" },
  { value: "IEEE CPMT", label: "IEEE CPMT (IEEE Electronics Packaging Society)" },
  { value: "IEEE CSS", label: "IEEE CSS (IEEE Control Systems Society)" },
  { value: "IEEE CTSoc", label: "IEEE CTSoc (IEEE Consumer Technology Society)" },
  { value: "IEEE DEIS", label: "IEEE DEIS (IEEE Dielectrics and Electrical Insulation Society)" },
  { value: "IEEE EDS", label: "IEEE EDS (IEEE Electron Devices Society)" },
  { value: "IEEE EdSoc", label: "IEEE EdSoc (IEEE Education Society)" },
  { value: "IEEE EMBS", label: "IEEE EMBS (IEEE Engineering in Medicine and Biology Society)" },
  { value: "IEEE EMCS", label: "IEEE EMCS (IEEE Electromagnetic Compatibility Society)" },
  { value: "IEEE GRSS", label: "IEEE GRSS (IEEE Geoscience & Remote Sensing Society)" },
  { value: "IEEE IAS", label: "IEEE IAS (IEEE Industry Applications Society)" },
  { value: "IEEE IES", label: "IEEE IES (IEEE Industrial Electronics Society)" },
  { value: "IEEE IMS", label: "IEEE IMS (IEEE Instrumentation and Measurement Society)" },
  { value: "IEEE ITSoc", label: "IEEE ITSoc (IEEE Information Theory Society)" },
  { value: "IEEE ITSS", label: "IEEE ITSS (IEEE Intelligent Transportation Systems Society)" },
  { value: "IEEE LEOS", label: "IEEE LEOS (IEEE Photonics Society)" },
  { value: "IEEE Magnetics", label: "IEEE Magnetics (IEEE Magnetics Society)" },
  { value: "IEEE MTT-S", label: "IEEE MTT-S (IEEE Microwave Theory and Techniques Society)" },
  { value: "IEEE NPSS", label: "IEEE NPSS (IEEE Nuclear and Plasma Sciences Society)" },
  { value: "IEEE OES", label: "IEEE OES (IEEE Oceanic Engineering Society)" },
  { value: "IEEE PCS", label: "IEEE PCS (IEEE Professional Communication Society)" },
  { value: "IEEE PELS", label: "IEEE PELS (IEEE Power Electronics Society)" },
  { value: "IEEE PES", label: "IEEE PES (IEEE Power & Energy Society)" },
  { value: "IEEE PSES", label: "IEEE PSES (IEEE Product Safety Engineering Society)" },
  { value: "IEEE RAS", label: "IEEE RAS (IEEE Robotics & Automation Society)" },
  { value: "IEEE RFID", label: "IEEE RFID (IEEE Council on RFID)" },
  { value: "IEEE RS", label: "IEEE RS (IEEE Reliability Society)" },
  { value: "IEEE SMCS", label: "IEEE SMCS (IEEE Systems, Man, and Cybernetics Society)" },
  { value: "IEEE SPS", label: "IEEE SPS (IEEE Signal Processing Society)" },
  { value: "IEEE SSCS", label: "IEEE SSCS (IEEE Solid-State Circuits Society)" },
  { value: "IEEE SSIT", label: "IEEE SSIT (IEEE Society on Social Implications of Technology)" },
  { value: "IEEE TCSC", label: "IEEE TCSC (IEEE Technical Community on Scalable Computing)" },
  { value: "IEEE TEMS", label: "IEEE TEMS (IEEE Technology & Engineering Management Society)" },
  { value: "IEEE UFFCS", label: "IEEE UFFCS (IEEE Ultrasonics, Ferroelectrics, & Frequency Control)" },
  { value: "IEEE VTS", label: "IEEE VTS (IEEE Vehicular Technology Society)" },
  { value: "IEEJ", label: "IEEJ (The Institute of Electrical Engineers of Japan)" },
  { value: "IEICE", label: "IEICE (Institute of Electronics, Information and Communication Engineers)" },
  { value: "IET", label: "IET (Institution of Engineering and Technology)" },
  { value: "IFIP", label: "IFIP (International Federation for Information Processing)" },
  { value: "IFSA", label: "IFSA (International Fuzzy Systems Association)" },
  { value: "IMechE", label: "IMechE (Institution of Mechanical Engineers)" },
  { value: "INCOSE", label: "INCOSE (International Council on Systems Engineering)" },
  { value: "INNS", label: "INNS (International Neural Networks Society)" },
  { value: "International Fuzzy", label: "International Fuzzy (IFSA)" },
  { value: "International Neural", label: "International Neural (INNS)" },
  { value: "IPSJ", label: "IPSJ (Information Processing Society of Japan)" },
  { value: "IRSI", label: "IRSI (Indonesia Researcher and Scientist Institute)" },
  { value: "ISCB", label: "ISCB (International Society for Computational Biology)" },
  { value: "ISCIE", label: "ISCIE (The Institute of Systems, Control and Information Engineers)" },
  { value: "ISI-ET", label: "ISI-ET (Integral SatCom Initiative)" },
  { value: "ISIF", label: "ISIF (International Society of Information Fusion)" },
  { value: "JAFS", label: "JAFS (Japanese Academy of Facial Studies)" },
  { value: "JAMI", label: "JAMI (Japan Association for Medical Informatics)" },
  { value: "JAMS", label: "JAMS (Japanese Association for Mathematical Sociology)" },
  { value: "Japan Research Textile", label: "Japan Research Textile (The Japan Research Association for Textile End-Users)" },
  { value: "JASESS", label: "JASESS (The Japan Association for Social and Economic Systems Studies)" },
  { value: "JES", label: "JES (Japan Ergonomics Society)" },
  { value: "JIAM", label: "JIAM (Japan Industrial Management Association)" },
  { value: "JNNS", label: "JNNS (Japanese Neural Network Society)" },
  { value: "JPA", label: "JPA (The Japanese Psychological Association)" },
  { value: "JSAI", label: "JSAI (The Japanese Society for Artificial Intelligence)" },
  { value: "JSCE", label: "JSCE (Japan Society of Civil Engineers)" },
  { value: "JSCES", label: "JSCES (The Japan Society for Computational Engineering And Science)" },
  { value: "JSDD", label: "JSDD (Japanese Society for The Science of Design)" },
  { value: "JSEC", label: "JSEC (The Japanese Society for Evolutionary Computation)" },
  { value: "JSET", label: "JSET (Japan Society for Educational Technology)" },
  { value: "JSIAM", label: "JSIAM (The Japan Society for Industrial and Applied Mathematics)" },
  { value: "JSKE", label: "JSKE (Japan Society of Kansei Engineering)" },
  { value: "JSMBE", label: "JSMBE (Japanese Society for Medical and Biological Engineering)" },
  { value: "JSME", label: "JSME (The Japan Society of Mechanical Engineers)" },
  { value: "KDCS", label: "KDCS (Korea Digital Contents Society)" },
  { value: "KICS", label: "KICS (Korea Information and Communications Society)" },
  { value: "KIIS", label: "KIIS (The Korean Institute of Intelligent Systems)" },
  { value: "MALTESAS", label: "MALTESAS (Malaysia Technical Scientist Association)" },
  { value: "MITS", label: "MITS (Malaysian Information Technology Society)" },
  { value: "MSJ", label: "MSJ (The Mathematical Society of Japan)" },
  { value: "MYTRIBOS", label: "MYTRIBOS (Malaysian Tribology Society)" },
  { value: "ORSJ", label: "ORSJ (The Operations Research Society of Japan)" },
  { value: "Royal Society of Chemistry", label: "Royal Society of Chemistry" },
  { value: "RSJ", label: "RSJ (The Robotics Society of Japan)" },
  { value: "S2", label: "S2 (Services Society)" },
  { value: "SBJ", label: "SBJ (The Society for Biotechnology, Japan)" },
  { value: "SBMO", label: "SBMO (Sociedade Brasileira de Micro-ondas e Optoeletrônica)" },
  { value: "SBrT", label: "SBrT (Brazilian Telecommunications Society)" },
  { value: "SCEJ", label: "SCEJ (The Society of Chemical Engineers, Japan)" },
  { value: "SCS", label: "SCS (Society for Modeling & Simulation International)" },
  { value: "SI", label: "SI (Schweizerische Gesellschaft für Informatik)" },
  { value: "SIAM", label: "SIAM (Society for Industrial and Applied Mathematics)" },
  { value: "SICE", label: "SICE (The Society of Instrument and Control Engineers)" },
  { value: "SMPTE", label: "SMPTE (Society of Motion Picture and Television Engineers)" },
  { value: "SOFT", label: "SOFT (Japan Society for Fuzzy Theory and intelligent informatics)" },
  { value: "SOFT Hokkaido", label: "SOFT Hokkaido (SOFT Hokkaido Chapter)" },
  { value: "SOTVI", label: "SOTVI" },
  { value: "SPE", label: "SPE (Society of Petroleum Engineers)" },
  { value: "SPIE", label: "SPIE (International society for optics and photonics)" },
  { value: "STI", label: "STI (Society for Tourism Informatics)" },
  { value: "TRON Forum", label: "TRON Forum" },
  { value: "UK Simulation Society", label: "UK Simulation Society" },
  { value: "URSI", label: "URSI (International Union of Radio Science)" },
  { value: "USENIX", label: "USENIX (Advanced Computing Systems Association)" },
  { value: "USNC-URSI", label: "USNC-URSI (U.S. National Committee for the International Union of Radio Science)" },
  { value: "VDE", label: "VDE (Verband der Elektrotechnik Elektronik Informationstechnik e.V.)" },
  { value: "VRSJ", label: "VRSJ (The Virtual Reality Society of Japan)" },
  { value: "VSF", label: "VSF (Video Services Forum)" },
] as const
